title: ExtremeRoles Wiki
description: ExtremeRoles公式Wiki
theme: just-the-docs

url: https://yukieiji.github.io/ExtremeRoles.Doc

search_enabled: true
# Maximum amount of previews per search result
# Default: 3
search.previews: 3

# Maximum amount of words to display before a matched word in the preview
# Default: 5
search.preview_words_before: 5

# Maximum amount of words to display after a matched word in the preview
# Default: 10
search.preview_words_after: 10

search.button: true

aux_links:
  ExtremeRoles リポジトリ: https://github.com/yukieiji/ExtremeRoles
