[project]
name = "extremeroles-docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jsonargparse>=4.41.0",
    "pytest>=8.4.2",
]
